In [2]:
#### 1. Import the numpy package under the name `np` (★☆☆)



import numpy as np

In [3]:
#### 2. Print the numpy version and the configuration (★☆☆)



print(np.__version__)
np.show_config()

1.23.1
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

In [3]:
#### 3. Create a null vector of size 10 (★☆☆)



Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#4. How to find the memory size of any array (★☆☆)



Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


800 bytes


In [10]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)



#%run `python -c "import numpy; numpy.info(numpy.add)"`


In [11]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)



Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)



Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)



Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [14]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)



Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)



nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4], dtype=int64),)


In [18]:
#### 11. Create a 3x3 identity matrix (★☆☆)



Z = np.identity(3)
# z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#### 12. Create a 3x3x3 array with random values (★☆☆)



Z = np.random.random((3,3,3))
print(Z)

[[[0.24302562 0.26699439 0.60487903]
  [0.57414144 0.70346238 0.7855302 ]
  [0.25258279 0.33207921 0.88435198]]

 [[0.10604345 0.28453035 0.26045479]
  [0.1886064  0.6653048  0.12923942]
  [0.35931531 0.95097783 0.60530285]]

 [[0.35950602 0.77331445 0.08336092]
  [0.87270804 0.4367508  0.45625388]
  [0.14648761 0.37050101 0.42997818]]]


In [23]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)



Z = np.random.random((10,10))
# print(Z)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.002225786640312588 0.9994192648684893


In [24]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)



Z = np.random.random(30)
m = Z.mean()
print(m)

0.515458087054729


In [29]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)



Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [31]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)



Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [32]:
# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [33]:
#### 17. What is the result of the following expression? (★☆☆)

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1




print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


In [34]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)



Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [39]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)



Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)



print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [41]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)



Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [42]:
#### 22. Normalize a 5x5 random matrix (★☆☆)



Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.97008198 -0.95788223 -0.29514705  0.52061917  0.56456256]
 [ 0.98175457  1.40322405 -0.42512154 -1.196869   -1.42382223]
 [ 1.10141913 -0.69556341  0.50258353  1.12755759  0.23436   ]
 [ 1.07626698 -0.71896354 -1.61295778  0.85979186 -1.43498278]
 [-1.4469066   0.33933261  1.07691513 -0.08145983  1.47137079]]


In [44]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)



color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [45]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)



Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [46]:
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [47]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)



# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [48]:
#### 26. What is the output of the following script? (★☆☆)

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))




# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10
10
10


In [7]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z




Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [6]:
#### 28. What are the result of the following expressions? (★☆☆)

np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)




print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Shivam\AppData\Local\Temp\ipykernel_18488\4275562608.py:3: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\Shivam\AppData\Local\Temp\ipykernel_18488\4275562608.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\Shivam\AppData\Local\Temp\ipykernel_18488\4275562608.py:10: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Shivam\AppData\Local\Temp\ipykernel_18488\4275562608.py:11: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [51]:
#### 29. How to round away from zero a float array ? (★☆☆)



# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-8.  5.  7.  4. -2.  1.  3. -4.  7.  4.]
[-8.  5.  7.  4. -2.  1.  3. -4.  7.  4.]


In [4]:
#### 30. How to find common values between two arrays? (★☆☆)



Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 3 4 6 7 8]


In [5]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)



# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

In [8]:
#### 32. Is the following expressions true? (★☆☆)

np.sqrt(-1) == np.emath.sqrt(-1)




np.sqrt(-1) == np.emath.sqrt(-1)


C:\Users\Shivam\AppData\Local\Temp\ipykernel_18488\3954824495.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)
C:\Users\Shivam\AppData\Local\Temp\ipykernel_18488\3954824495.py:8: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [10]:

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)



yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2022-10-07
2022-10-08
2022-10-09


In [11]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)



Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [12]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)



A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [13]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)



Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[6. 6. 6. 7. 6. 8. 3. 4. 3. 4.]
[6. 6. 6. 7. 6. 8. 3. 4. 3. 4.]
[6. 6. 6. 7. 6. 8. 3. 4. 3. 4.]
[6 6 6 7 6 8 3 4 3 4]
[6. 6. 6. 7. 6. 8. 3. 4. 3. 4.]


In [14]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)



Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [15]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)



def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [16]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)



Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [17]:
#### 40. Create a random vector of size 10 and sort it (★★☆)



Z = np.random.random(10)
Z.sort()
print(Z)

[0.01137913 0.09589942 0.1178016  0.12569003 0.66099855 0.66600522
 0.84531365 0.85247692 0.91235948 0.9732118 ]


In [18]:
#### 41. How to sum a small array faster than np.sum? (★★☆)



# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)

45

In [19]:
#### 42. Consider two random array A and B, check if they are equal (★★☆)



A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [20]:
#### 43. Make an array immutable (read-only) (★★☆)



Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [21]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)



Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


[0.58286146 0.99569426 0.81808381 1.27826739 0.81351289 0.30346533
 1.07981087 0.97524269 0.91647718 0.14677691]
[0.70088535 0.89065306 0.77259528 0.77939986 1.36904233 0.68223917
 0.40775019 0.06572564 0.13726665 0.64952494]


In [23]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)



Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.44464358 0.         0.70234068 0.81404591 0.6013911  0.54948737
 0.69549713 0.11224529 0.26788993 0.49064141]


In [24]:
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)



Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [25]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)



# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [26]:
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)



for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [27]:
#### 49. How to print all the values of an array? (★★☆)



np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)



Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


12


In [29]:
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)



Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Shivam\AppData\Local\Temp\ipykernel_18488\1833048594.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [31]:
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)



Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)


[[0.         0.30890822 0.34928267 0.84211083 0.8120782  0.1475627
  0.67396158 0.33884881 0.64352475 0.57468857]
 [0.30890822 0.         0.12731548 0.5334552  0.53311624 0.16810888
  0.3748105  0.19436695 0.43524426 0.26980311]
 [0.34928267 0.12731548 0.         0.53828206 0.46287527 0.20449948
  0.33659446 0.32166458 0.31983145 0.31009385]
 [0.84211083 0.5334552  0.53828206 0.         0.3184392  0.70025304
  0.23516678 0.58621671 0.52130719 0.27287408]
 [0.8120782  0.53311624 0.46287527 0.3184392  0.         0.66608271
  0.18525359 0.67598858 0.26361814 0.3936357 ]
 [0.1475627  0.16810888 0.20449948 0.70025304 0.66608271 0.
  0.526515   0.26206557 0.51183152 0.4378189 ]
 [0.67396158 0.3748105  0.33659446 0.23516678 0.18525359 0.526515
  0.         0.49728551 0.29440549 0.20905048]
 [0.33884881 0.19436695 0.32166458 0.58621671 0.67598858 0.26206557
  0.49728551 0.         0.62151601 0.31921518]
 [0.64352475 0.43524426 0.31983145 0.52130719 0.26361814 0.51183152
  0.29440549 0.62151601

In [32]:
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.53513323 0.15023315 0.59179806 0.53817636 0.21468337
  0.53302988 0.85512876 0.52635304 0.37524978]
 [0.53513323 0.         0.67831201 0.30008397 0.94085992 0.74981261
  0.21752277 0.61175071 0.76993459 0.86023753]
 [0.15023315 0.67831201 0.         0.69744812 0.42907718 0.08863429
  0.65040095 0.92810031 0.48790621 0.23816594]
 [0.59179806 0.30008397 0.69744812 0.         0.81445349 0.78399075
  0.08926012 0.32206472 0.58386086 0.80547762]
 [0.53817636 0.94085992 0.42907718 0.81445349 0.         0.45855
  0.8143756  0.90329592 0.27108277 0.21874981]
 [0.21468337 0.74981261 0.08863429 0.78399075 0.45855    0.
  0.7344593  1.0166363  0.55652425 0.24632379]
 [0.53302988 0.21752277 0.65040095 0.08926012 0.8143756  0.7344593
  0.         0.4112754  0.60380141 0.78144716]
 [0.85512876 0.61175071 0.92810031 0.32206472 0.90329592 1.0166363
  0.4112754  0.         0.63398571 0.9681049 ]
 [0.52635304 0.76993459 0.48790621 0.58386086 0.27108277 0.55652425
  0.60380141 0.63398571 0

In [33]:
#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?



# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[33  0 97 18 46  9 57 95 87 68]


In [35]:
#### 54. How to read the following file? (★★☆)

# 1, 2, 3, 4, 5
# 6,  ,  , 7, 8
#  ,  , 9,10,11




from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\Shivam\AppData\Local\Temp\ipykernel_18488\30529660.py:17: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


In [36]:
#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)



Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [37]:
### 56. Generate a generic 2D Gaussian-like array (★★☆)



X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [38]:
#### 57. How to randomly place p elements in a 2D array? (★★☆)



# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
#### 58. Subtract the mean of each row of a matrix (★★☆)



# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.51485676 -0.10054837  0.09207473  0.40020101 -0.40906813  0.39041552
  -0.18186851  0.24647132  0.40339444 -0.32621526]
 [ 0.01401035  0.20693506 -0.53311123 -0.0869708  -0.04345538  0.184794
  -0.26847007  0.33567122  0.24832971 -0.05773287]
 [-0.47019816  0.06374803 -0.05212473  0.30888259  0.42940268 -0.03631447
  -0.2602218   0.12558714 -0.105402   -0.00335927]
 [-0.42749236  0.01120349  0.04427857  0.03945396 -0.42122824  0.24941417
  -0.43230546  0.32940029  0.44159434  0.16568124]
 [ 0.22523665  0.13372508 -0.15346895 -0.06072827  0.28792333 -0.445805
  -0.48090036  0.42319978 -0.21429526  0.285113  ]]


In [40]:
#### 59. How to sort an array by the nth column? (★★☆)



# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


[[0 5 8]
 [4 1 2]
 [8 6 2]]
[[4 1 2]
 [0 5 8]
 [8 6 2]]


In [41]:
#### 60. How to tell if a given 2D array has null columns? (★★☆)



# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())


True


In [42]:
#### 61. Find the nearest value from a given value in an array (★★☆)



Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5144677497956384


In [43]:
#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)



A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [44]:
#### 63. Create an array class that has a name attribute (★★☆)



class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [45]:
#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)



# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[4. 4. 4. 2. 2. 1. 3. 5. 3. 2.]
[7. 7. 7. 3. 3. 1. 5. 9. 5. 3.]


In [46]:
#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)



# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [47]:
#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)



# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


In [48]:
#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)



A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[57 39 51 56]
 [48 55 63 53]
 [32 41 40 42]]
[[57 39 51 56]
 [48 55 63 53]
 [32 41 40 42]]


In [49]:
#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)



# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


[0.31380866 0.50072276 0.52319286 0.63465583 0.4667331  0.47541185
 0.45276882 0.57963765 0.54161135 0.52560913]
0    0.313809
1    0.500723
2    0.523193
3    0.634656
4    0.466733
5    0.475412
6    0.452769
7    0.579638
8    0.541611
9    0.525609
dtype: float64


In [50]:
#### 69. How to get the diagonal of a dot product? (★★★)



# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


array([1.52201976, 0.89136557, 0.92575643, 1.86877781, 1.33380044])

In [51]:
#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)



# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [52]:
#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)



A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [53]:
#### 72. How to swap two rows of an array? (★★★)



# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [54]:
#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)



# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 23) ( 4, 51) ( 5, 66) (13, 20) (13, 53) (20, 53) (22, 73) (23, 51)
 (25, 74) (25, 93) (37, 49) (37, 60) (43, 87) (49, 60) (51, 91) (51, 96)
 (66, 66) (66, 69) (66, 88) (69, 88) (73, 73) (74, 93) (80, 83) (80, 93)
 (83, 93) (87, 87) (91, 96)]


In [55]:
#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)



# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


[1 1 2 3 4 4 6]


In [56]:
#### 75. How to compute averages using a sliding window over an array? (★★★)



# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

# Author: Jeff Luo (@Jeff1999)
# make sure your NumPy >= 1.20.0

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [57]:
#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)



# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [58]:

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)



# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


array([ 0.62627669, -0.7758281 ,  0.05763356,  0.81272009, -0.22355247,
        0.26722031, -0.02771789,  0.24314226, -0.75501009,  0.81271793,
       -0.43842004,  0.38104451, -0.49423682,  0.65506387,  0.6636576 ,
       -0.18749488, -0.02974475, -0.00709458, -0.76249476, -0.03802809,
       -0.87557944,  0.57233783,  0.31557459,  0.37697065, -0.99015173,
        0.48145846, -0.06208718, -0.87483525,  0.71000066, -0.32927318,
        0.28144092, -0.91500326,  0.13497952,  0.43039073,  0.46281892,
        0.90904736, -0.65839595, -0.06167024,  0.31388934,  0.96778789,
        0.59538438,  0.53730957, -0.801769  ,  0.6002972 ,  0.89137272,
       -0.09092725,  0.57126589, -0.42835073,  0.57606466,  0.19215657,
        0.53198558,  0.86960293, -0.21317834,  0.2600029 , -0.1382351 ,
        0.19770266, -0.42338416,  0.62104184, -0.60520133,  0.53271348,
       -0.35615875, -0.0750938 ,  0.19685467, -0.09615673,  0.83312126,
       -0.96202712, -0.52219189,  0.98949371, -0.39435145, -0.08

In [59]:
#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)



def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


[1.80548276 0.04504075 3.51474177 9.29734883 3.04169717 1.62953922
 7.05801469 2.00033797 2.96722755 2.26620692]


In [60]:

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)



# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 9.10982624  0.35563187  2.51757247  0.21537304  2.45652115  6.13888653
  12.74644516  0.15274095  6.11231006  5.61454155]
 [ 1.83246998 12.51376877 14.80542571 10.11283322  8.97397007  3.07326598
   0.90032689  7.66097202  4.24124306  0.68884144]
 [ 9.54670783  2.87822308  5.50204465 10.8518279   7.52290102  5.80860859
  11.15528479  5.09549072 15.98406219 12.12358238]
 [16.61865402  5.11910916  2.60079769  3.64402546  0.34886332  3.26717982
  18.90715748  9.9305472  16.7386649  15.90703459]
 [ 0.33396987  8.82407563 10.89090936  3.17341903  2.26135015  8.82647681
   4.12579724  8.08838465  0.43451136  2.10881309]
 [ 8.14701222  0.96960802  3.07218642  1.04614898  3.03213933  7.69815375
  12.0168914   1.23651399  4.46307871  4.11169501]
 [14.13462062  4.94699562  2.80106949  3.88772713  6.73238299  6.42115334
  17.99380666  4.17267399  7.88507369  9.09259468]
 [ 7.17216419  2.10401025  4.22610044  0.06951952  1.83604675  7.21945329
  10.92636398  1.8537615   4.46325717  3.65670815]


In [61]:
#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)



# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [62]:
#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)



# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [63]:
#### 82. Compute a matrix rank (★★★)



# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:
# Author: Jeff Luo (@Jeff1999)

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


In [64]:
#### 83. How to find the most frequent value in an array?



Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


In [65]:
#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)



# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

# Author: Jeff Luo (@Jeff1999)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[0 4 1]
   [1 1 3]
   [3 4 4]]

  [[4 1 3]
   [1 3 1]
   [4 4 3]]

  [[1 3 1]
   [3 1 1]
   [4 3 1]]

  [[3 1 3]
   [1 1 1]
   [3 1 4]]

  [[1 3 1]
   [1 1 4]
   [1 4 1]]

  [[3 1 3]
   [1 4 0]
   [4 1 1]]

  [[1 3 4]
   [4 0 3]
   [1 1 2]]

  [[3 4 1]
   [0 3 2]
   [1 2 3]]]


 [[[1 1 3]
   [3 4 4]
   [0 4 3]]

  [[1 3 1]
   [4 4 3]
   [4 3 2]]

  [[3 1 1]
   [4 3 1]
   [3 2 1]]

  [[1 1 1]
   [3 1 4]
   [2 1 3]]

  [[1 1 4]
   [1 4 1]
   [1 3 3]]

  [[1 4 0]
   [4 1 1]
   [3 3 1]]

  [[4 0 3]
   [1 1 2]
   [3 1 0]]

  [[0 3 2]
   [1 2 3]
   [1 0 0]]]


 [[[3 4 4]
   [0 4 3]
   [3 0 3]]

  [[4 4 3]
   [4 3 2]
   [0 3 0]]

  [[4 3 1]
   [3 2 1]
   [3 0 1]]

  [[3 1 4]
   [2 1 3]
   [0 1 3]]

  [[1 4 1]
   [1 3 3]
   [1 3 3]]

  [[4 1 1]
   [3 3 1]
   [3 3 1]]

  [[1 1 2]
   [3 1 0]
   [3 1 1]]

  [[1 2 3]
   [1 0 0]
   [1 1 2]]]


 [[[0 4 3]
   [3 0 3]
   [1 2 3]]

  [[4 3 2]
   [0 3 0]
   [2 3 3]]

  [[3 2 1]
   [3 0 1]
   [3 3 1]]

  [[2 1 3]
   [0 1 3]
   [3 1 3]]

  [[1 3 3]
   

In [66]:
#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)



# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7  6 17  9  8]
 [ 6  2  9 17 14]
 [17  9  7 42 14]
 [ 9 17 42  9 10]
 [ 8 14 14 10  4]]


In [67]:
#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)



# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [68]:
#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)



# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:
# Author: Sebastian Wallkötter (@FirefoxMetzger)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

# Author: Jeff Luo (@Jeff1999)

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [69]:
#### 88. How to implement the Game of Life using numpy arrays? (★★★)



# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 1 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 1 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0

In [70]:
#### 89. How to get the n largest values of an array (★★★)



Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9999 9997 9995 9998]


In [71]:
#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)



# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [72]:
#### 91. How to create a record array from a regular array? (★★★)



Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [73]:
#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)



# Author: Ryan G.

x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


4 s ± 60.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
454 ms ± 13.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
298 ms ± 6.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [74]:
#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)



# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 5 7]


In [75]:
#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)



# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 2 3]
 [0 0 3]
 [2 2 1]
 [3 3 2]
 [1 1 2]
 [3 1 3]
 [3 4 3]
 [4 2 0]
 [4 3 2]
 [1 3 4]]
[[2 2 3]
 [0 0 3]
 [2 2 1]
 [3 3 2]
 [1 1 2]
 [3 1 3]
 [3 4 3]
 [4 2 0]
 [4 3 2]
 [1 3 4]]
[[2 2 3]
 [0 0 3]
 [2 2 1]
 [3 3 2]
 [1 1 2]
 [3 1 3]
 [3 4 3]
 [4 2 0]
 [4 3 2]
 [1 3 4]]


In [76]:
#### 95. Convert a vector of ints into a matrix binary representation (★★★)



# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [78]:
#### 96. Given a two dimensional array, how to extract unique rows? (★★★)



# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [79]:
#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)



# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.13255191, 0.32920439, 0.18091739, 0.10121037, 0.16199231,
        0.64393215, 0.51621249, 0.62505702, 0.20200414, 0.36019479],
       [0.06145569, 0.15263064, 0.08387961, 0.04692466, 0.07510529,
        0.29854941, 0.23933411, 0.28979824, 0.09365617, 0.16699887],
       [0.12010123, 0.29828203, 0.16392371, 0.09170363, 0.14677628,
        0.58344724, 0.46772435, 0.56634506, 0.18302978, 0.32636149],
       [0.18490591, 0.45923019, 0.2523743 , 0.14118542, 0.22597439,
        0.89826594, 0.72010085, 0.8719357 , 0.28178968, 0.50246087],
       [0.03860302, 0.09587401, 0.05268847, 0.02947544, 0.04717693,
        0.187532  , 0.15033628, 0.18203501, 0.05882955, 0.10489933],
       [0.18812191, 0.46721741, 0.25676376, 0.14364101, 0.22990468,
        0.91388915, 0.73262531, 0.88710096, 0.28669075, 0.51119999],
       [0.06764457, 0.16800127, 0.09232669, 0.0516502 , 0.08266875,
        0.32861476, 0.2634362 , 0.3189823 , 0.10308779, 0.18381645],
       [0.09726742, 0.24157226, 0.1327583

In [83]:
#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?



# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
print(r_int)
print(x_int)
print(y_int)
print(r)
print(dr)


[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

In [84]:
#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)



# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


[[2. 0. 1. 1.]]


In [85]:
#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)



# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.34170631  0.09390149]
