In [2]:
import numpy as np

In [3]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
arr12[2]

array([ 8,  9, 10, 11])

In [5]:
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
arr12[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [8]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [9]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [10]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [11]:
arr12[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [12]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [14]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [15]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [16]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [17]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [18]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [19]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [20]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [22]:
arr4.max()

11

In [23]:
arr4.min()

6

In [24]:
arr4.min(axis=0)   #axis means column wish lowest

array([6, 7])

In [25]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [26]:
arr4.sum()

51

In [27]:
arr4.sum(axis=0)

array([24, 27])

In [28]:
arr4.sum(axis=1)

array([13, 17, 21])

In [29]:
arr4.mean()

8.5

In [30]:
arr4.mean(axis=0)

array([8., 9.])

In [31]:
arr4.std()

1.707825127659933

In [32]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [33]:
np.median(arr4)

8.5

In [34]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [35]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [36]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [37]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [38]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
arr5=np.arange(12,18).reshape(2,3)
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [40]:
np.hstack((arr3,arr5)) #horizontal

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [41]:
np.vstack((arr3,arr5))    #vertical

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [42]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [45]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [46]:
arr8=np.arange(24).reshape(6,4)

In [47]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])