In [1]:
import numpy as np

In [2]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

array([[41, 85, 36, 51,  5],
       [66, 82, 14, 11, 98],
       [ 5, 34, 71, 82, 22],
       [16, 78, 68, 63, 26]])

In [3]:
arr>50

array([[False,  True, False,  True, False],
       [ True,  True, False, False,  True],
       [False, False,  True,  True, False],
       [False,  True,  True,  True, False]])

In [4]:
arr[arr>50]     #indexing/filtering suing boolean arrays

array([85, 51, 66, 82, 98, 71, 82, 78, 68, 63])

In [6]:
arr[(arr>50)&(arr%2!=0)]

array([85, 51, 71, 63])

In [7]:
arr[(arr>50)&(arr%2!=0)]=0
arr

array([[41,  0, 36,  0,  5],
       [66, 82, 14, 11, 98],
       [ 5, 34,  0, 82, 22],
       [16, 78, 68,  0, 26]])