In [1]:
import numpy as np

In [2]:
np.random.random()

0.02659936311683453

In [4]:
np.random.seed(1)    #same random value again and again
np.random.random()

0.417022004702574

In [5]:
np.random.uniform(1,100)

72.31212485077366

In [6]:
np.random.uniform(1,100,10)

array([ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093,
       35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054])

In [8]:
np.random.uniform(1,10)

8.90305692751851

In [10]:
np.random.uniform(1,100,10).reshape(2,5)

array([[87.76252608, 89.56605969,  9.41937693,  4.86642354, 17.81321154],
       [87.93610784, 10.73633655, 42.68965488, 95.83106348, 53.78336321]])

In [12]:
np.random.randint(1,10)

9

In [14]:
np.random.randint(1,10,5)

array([1, 5, 3, 8, 8])

In [15]:
np.random.randint(1,10,15).reshape(3,5)

array([[9, 7, 4, 8, 8],
       [5, 6, 4, 7, 9],
       [1, 3, 8, 8, 8]])

In [17]:
a=np.random.randint(1,10,5)
a

array([2, 2, 4, 1, 9])

In [18]:
np.max(a)

9

In [19]:
np.min(a)

1

In [20]:
np.argmax(a)

4

In [21]:
a[np.argmax(a)]

9

In [22]:
np.argmin(a)

3

In [23]:
a=np.random.randint(1,10,6)
a

array([7, 5, 6, 7, 3, 6])

In [24]:
a[a%2==1]=-1
a

array([-1, -1,  6, -1, -1,  6])

In [26]:
# where(condition,True,False)
a=np.random.randint(1,50,6)
a

array([44, 21, 31, 37, 40,  8])

In [27]:
np.where(a%2==1,-1,a)

array([44, -1, -1, -1, 40,  8])

In [28]:
a

array([44, 21, 31, 37, 40,  8])

In [29]:
b=np.where(a%2==1,-1,a)
b

array([44, -1, -1, -1, 40,  8])

In [30]:
a=np.random.randint(1,50,10)
a

array([46,  5, 49, 19, 33, 14, 11, 24, 18,  8])

In [31]:
a=np.sort(a)
a

array([ 5,  8, 11, 14, 18, 19, 24, 33, 46, 49])

In [32]:
np.percentile(a,25)

11.75

In [33]:
np.percentile(a,50)

18.5

In [34]:
np.percentile(a,99.8)

48.946